services:
  app:
    build: .
    container_name: splitwise-app
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: splitwise
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mysql-network

  mysql:
    image: mysql:8.0.45-debian
    container_name: splitwise-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: splitwise
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mysql-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: splitwise-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:
